services:
  frontend:
    build: ./public
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  backend:
    build: ./server
    ports:
      - "5000:5000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"


# version: '3.8'

# services:
#   frontend:
#     build: ./public
#     ports:
#       - "3000:3000"

#   backend:
#     build: ./server
#     ports:
#       - "5000:5000"

#   mongo:
    # image: mongo
    # ports:
